name: Pre-merge checks

on:
  pull_request:
    types: [opened, ready_for_review, reopened, synchronize]

jobs:
  pre-merge-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 24.3.0

      - name: Code Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm ci

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Code Linting
        run: npx eslint .

      - name: Unit Tests
        run: npm run test:coverage